{% set name = "code2flow" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/code2flow-{{ version }}.tar.gz
  sha256: a651e839480ac744427d596cc582149bee39bf19d05b374e69c55f65f0e13406

build:
  number: 0
  noarch: python
  entry_points:
    - code2flow=code2flow.engine:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - code2flow
  commands:
    - pip check
    - code2flow --help
  requires:
    - pip

about:
  home: https://github.com/scottrogowski/code2flow
  summary: Visualize your source code as DOT flowcharts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
